---
- hosts: all
  become: true
  pre_tasks:
    - import_tasks: tasks/cmdline_setup.yml

  roles:
    - role: nicholasburr.meta
    - role: nicholasburr.docker_ce
    - role: nicholasburr.kubernetes

  handlers:
    - name: reboot
      reboot:
