---
- name: enabling cgroup options
  lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '^(.*fixrtc)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    state: present
    backrefs: true
  notify: reboot
