---
- name: enabling cgroup options
  lineinfile:
    path: /boot/firmware/cmdline.txt
    line: 'cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    regexp: "(fixrtc)$"
    backrefs: true
    state: present
  notify: reboot
